export const AGREGAR_EVENTO = "AGREGAR_EVENTO";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTRAR_ASISTENCIA = "REGISTRAR_ASISTENCIA";
export const INSCRIPCION_EVENTO = "INSCRIPCION_EVENTO";
export const AGREGAR_TIPO_USUARIO = "AGREGAR_TIPO_USUARIO";