export const GUARDAR_AGREGAR_EVENTO = "GUARDAR_AGREGAR_EVENTO";
export const GUARDAR_AGREGAR_TIPO_EVENTO = "GUARDAR_AGREGAR_TIPO_EVENTO";
export const GUARDAR_LOGIN = "GUARDAR_LOGIN";
export const ACTIVAR_SPINNER = "ACTIVAR_SPINNER";
export const DESACTIVAR_SPINNER = "DESACTIVAR_SPINNER";
export const GUARDAR_INSCRIPCION_EVENTO = "GUARDAR_INSCRIPCION_EVENTO";
export const GUARDAR_TIPO_USUARIO = "GUARDAR_TIPO_USUARIO";